server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
spring:
  application:
    name: web-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nxin_etl_2024_001_mybatis?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 1qaz@WSX
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句
    validationQuery: SELECT 1
    # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false
    # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: true
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    max-pool-prepared-statement-per-connection-size: 50
    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,log4j
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE-DATES-AS-TIMESTAMPS: false
  mail:
    host:
    port:
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    from:
    forgotSubject: 新恩数造找回密码
  # 根据实际情况配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    username:
    password:
  data:
    redis:
      repositories:
        enabled: false
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    settings:
      classic_compatible: true
      default_encoding: UTF-8
      template_update_delay: 0
    suffix: .ftl
    template-loader-path: classpath:/templates/
mybatis-plus:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  secret: nxin
  expirationDateInMs: 0
  refreshExpirationDateInMs: 9000000
# etl脚本调试时生成的附件存放位置
attachment:
  dir: ${user.home}/.etl-designer/attachment/
# etl脚本调试时脚本存放位置
dev:
  dir: ${user.home}/.etl-designer/dev/
# etl脚本调试时拉取数据文件（excel，csv等）存放位置
download:
  dir: ${user.home}/.etl-designer/download/
setting:
  trans:
    records-size: 10000
    row-size: 50000
    feedback: true
    thread-manage-priority: true
    engine: Normal
etl:
  log:
    datasource:
      name: nxin_etl_2024_001_mybatis
      type: Mysql
      access: JDBC
      host: localhost
      port: 3306
      schema: nxin_etl_2024_001_mybatis
      username: root
      password: 1qaz@WSX
    send-delay: 1
springfox:
  documentation:
    swagger-ui:
      enabled: true
# 新建用户初始密码
init:
  password: 123456
# etl脚本创建后，脚本文件存放的sftp信息
vfs:
  lang: zh
  host: 127.0.0.1:22
  path: /Documents/
  schema: sftp
  username: nxin
  password: 1qaz@WSX
  privateKey:
  passPhrase:
# web与worker集群通讯的web控制地址
worker:
  schedule-create-job-uri: http://127.0.0.1:8001/schedule/create
  schedule-find-all-cron-trigger-uri: http://127.0.0.1:8001/schedule/findAllCronTrigger
  schedule-pause-uri: http://127.0.0.1:8001/schedule/pause
  schedule-stop-uri: http://127.0.0.1:8001/schedule/stop
  schedule-resume-uri: http://127.0.0.1:8001/schedule/resume
  schedule-modify-uri: http://127.0.0.1:8001/schedule/modify
  schedule-create-streaming-uri: http://127.0.0.1:8001/schedule/createStreaming
# web与worker集群通讯的消息控制方式（推送指令等）
message:
  sender: redis
logging:
  level:
    root: INFO
ai:
  url: http://localhost:11434/api/generate
  model: qwen2.5-coder:1.5b-base-q8_0